baseURL = "https://ipet.space"
languageCode = "en-us"
title = "iPet.Space"
disableKinds = ["sitemap", "RSS"]
theme = "webslides"
themesDir = "./themes/"
tags = ["宠物", "社群"]
features = ["webslides.js", "pre-made template", "shortcodes"]

[params]
  author = "iPet.Space"
  homepage = "ipet.space"


[params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
